Feature/reduxtoolkit implementation
ValoQuang/my-first-cra pull request #2
Opened 2024-07-01 06:36 UTC by ValoQuang

Feature: Add redux store
- Theme store
- Page store, Loading, Error, Data state handler
- Add Responsive 
- Add useFetch to fetch data from github api

2024-07-01 08:02 UTC, haola1210 requested changes

2024-07-01 08:02 UTC, haola1210 commented on src/pages/Navigation.tsx
> +            />
there is no href link popup at the bottom-left corner of the screen.

2024-07-01 08:02 UTC, haola1210 commented on src/pages/Navigation.tsx
> +      <div className="text-3xl">Quang Truong</div>
should navigate to index page when users click on this

2024-07-01 08:02 UTC, haola1210 commented on src/redux/page/pageSlice.tsx
> +export default pageSlice.reducer;
we can use `createApi` from `https://redux-toolkit.js.org/rtk-query/overview` to avoid this boilerplate

2024-07-01 08:02 UTC, haola1210 commented on src/redux/page/pageSlice.tsx
> +  data: any;
shouldnt be `any` Steven hates that

2024-07-01 08:02 UTC, haola1210 commented on src/redux/store.tsx
> +export const persistor = persistStore(store);
persist everything is not a good idea. 

in the prod of company, users can switch between their accounts and the data are diff. and persistent may lead to the stale data issue.

we maybe just need to persist the themes config i think

2024-07-01 08:02 UTC, haola1210 commented on src/redux/theme/themeSlice.tsx
> +const themes = ['light', 'dark', 'cupcake'];
add `as const` at the end and export this, we can reuse this as constants some where (or at line: 8 above) hehe

2024-07-01 08:02 UTC, haola1210 commented on src/utils/useFetch.tsx
> +          `GET /users/${process.env.REACT_APP_GITHUB_NAME}`,
there is no `.env.example` or a description in readme about this.
and i saw u use a raw value in a prev commit (a critical issue) 🩻

2024-07-01 08:02 UTC, haola1210 commented on src/utils/useFetch.tsx
> +export const useFetchGitHub = () => {
and again the `createApi` of rtk will help u out of this boilerplate

2024-07-01 08:04 UTC, haola1210 commented
custom hooks should be placed in `hooks` dir. 
all directories should have an `index.ts` file to export most of everything inside its dir.

2024-07-01 08:10 UTC, haola1210 commented
Footer, Navigation are parts of layout. we can place them in RootLayout component at `components/RootLayout`.

2024-07-01 10:25 UTC, ValoQuang commented
@haola1210 switched to rtk query, fixed the project folder structures, added href link, deleted unused hooks

2024-07-02 01:13 UTC, haola1210 approved these changes

2024-07-02 01:15 UTC, merged